config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  confirmations: 'users/confirmations',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  sessions:      'users/sessions',
  omniauth_callbacks: 'users/omniauth_callbacks'
}
  get '/login',to:"sessions#new"
  post '/login',to:"sessions#create"
  root 'memos#index'
  resources :memos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  scope :recent, -> {order(cerated_at: :desc)} #アロー演算子
end

app/models/memo.rb
class Memo < ApplicationRecord
    has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
         def self.find_for_oauth(auth)
          user = User.where(uid: auth.uid, provider: auth.provider).first
      
          unless user
            user = User.create(
              uid:      auth.uid,
              provider: auth.provider,
              email:    User.dummy_email(auth),
              password: Devise.friendly_token[0, 20]
            )
          end
          user
        end
      
        private
      
        def self.dummy_email(auth)
          "#{auth.uid}-#{auth.provider}@example.com"
        end
        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user #どこでも使いますよ
private def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
end
private def login_required
    redirect_to login_path unless current_user
end
end
#ヘルパーフォルダはあまり使わない

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  helper_method :search_memo
  before_action :set_memo,only:[:show,:destroy,:edit,:update]
  def index
    @memos = Memo.recent
  end
  def new
    @memo = Memo.new
  end
  def create
    @memo = Memo.new(memo_params)
    if @memo.save
      redirect_to memos_path,notice:"メモ「#{@memo.article}」を登録しました"
    else
      render 'new'
    end
  end
  def show
  end
  def destroy
    @memo.destroy
    redirect_to root_path,notice:"メモ「#{@memo.article}」を削除しました"
  end
  def edit
    
  end
  def update
    @memo.update!(memo_params)
      redirect_to root_path,notice:"メモ「#{@memo.article}」を更新しました"
  end

  private def memo_params
    params.require(:memo).permit(
      :article,
      :memo1,
      :memo2,
      :memo3,
      :memo4,
      :image
    )
  end
  private def search_memo
    @q = Memo.ransack(params[:q])
    @memos = @q.result(distinct: true).recent
  end
  private def set_memo
    @memo = Memo.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end
  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
    session[:user_id] = user.id
    redirect_to memos_path,notice:"ログインしました"
    else
      render :new
    end
  end
  def destroy
    reset_session
    redirect_to root_path,notice:'ログアウトしました'
  end

  private def session_params
    params.require(:session).permit(
      :email,
      :password
    )
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    callback_from :facebook
  end
 
  private
 
  def callback_from(provider)
    provider = provider.to_s
 
    @user = User.find_for_oauth(request.env['omniauth.auth'])
 
    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top bg-dark mb-4">
<div class="container">
<%= link_to "Memo", '/',style:"font-size:1.8rem;",class:"nav-link text-light" %>
<nav>
  <ul class="navbar list-inline" style="height:2.0rem;">
    <li class="list-inline-item"><%= link_to "新規メモ",new_memo_path %></li>
    <li class="list-inline-item"><%= link_to "新規登録", new_user_registration_path %></li>
    <li class="list-inline-item"><%= link_to "ログイン", new_user_session_path %></li>
    <li class="list-inline-item"><%= link_to "ログアウト", destroy_user_session_path,method: :delete %></li>
    </ul>
</nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeMo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <div class="container">
  <%= render "layouts/header" %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-info" >"><%= message %></div>
  <% end %>
  </div>
  
  <div class="box7">
  <div class="box7-1">
  <%= yield %>
  </div>
  <div class="box7-2">
  <% if current_user %>
  <%= render 'sidebar' %>
  <% end %>
  
  </div>
  </div>
  
  
  <div class="box5">
  <div class="box5-inner">
    <div class="copyright">
    <p>Copyright &copy; TimeSwitch</p>
    </div>
  </div>
  </div>
  
  
  </body>
  </html>

app/views/memos/_form.html.erb
<div class="container">
<%= form_with model:@memo,local:true do |f| %>
<div class="form-group row">
<%= f.label :article,class:"col-md-2 control-label" %>
<div class="col-md-10">
<%= f.text_field :article,class:"form-control is-valid" %>
</div>
</div>
<div class="form-group row">
<%= f.label :image,class:"col-md-2 control-label" %>
<div class="col-md-10">
<%= f.file_field :image,class:"form-control" %>
</div>
</div>
<div class="form-group row">
<%= f.label :memo1,class:"col-md-2 control-label" %>
<div class="col-md-10">
<%= f.text_area :memo1,class:"form-control form-control-lg" %>
</div>
</div>
<div class="form-group row">
<%= f.label :memo2,class:"col-md-2 control-label" %>
<div class="col-md-10">
<%= f.text_area :memo2,class:"form-control" %>
</div>
</div>
<div class="form-group row">
<%= f.label :memo3,class:"col-md-2 control-label" %>
<div class="col-md-10">
<%= f.text_area :memo3,class:"form-control" %>
</div>
</div>
<div class="form-group row">
<%= f.label :memo4,class:"col-md-2 control-label" %>
<div class="col-md-10">
<%= f.text_area :memo4,class:"form-control" %>
</div>
</div>
<%= f.submit "投稿する",class:'btn btn-primary float-right btn-block' %>
<% end %>
</div>

app/views/memos/_sidebar.html.erb
<%= search_form_for @q do |f| %>
    <table>
    <tr>
    <th><%= f.search_field :article_cont %></th>
    <td><%= f.submit '検索' %></td>
    </tr>
    </table>
    <% end %>
<aside class="sidemenu mt-3">
<ul>
<% @memos.each do |memo| %>
<li><%= link_to memo.article,memo_path(memo) %></li>
<% end %>
</ul>
</aside>

app/views/memos/edit.html.erb
<%= render 'form' %>

app/views/memos/index.html.erb
<article class="kiji">
<h3>メモ一覧</h3>
<table>
<% @memos.each do |memo| %>
<tr>
<td>・<%= link_to memo.article,memo_path(memo)%></td>
</tr>
<tr>
<td><%= truncate(memo.memo1,length:20) %></td>
</tr>
<% end %>
</table>
</article>

app/views/memos/new.html.erb
<%= render 'form' %>

app/views/memos/show.html.erb
<article class="kiji">
<h1><%= @memo.article %></h1>

<%= image_tag(@memo.image,alt:"" ,class:"kijiimg") if @memo.image.attached?  %>

<p class="lead"><%== @memo.memo1 %></p>


<div class="honbun">
<p><%== @memo.memo2 %></p>

<p><%== @memo.memo3 %></p>

<p><%== @memo.memo4 %></p>
<%= link_to '編集する',edit_memo_path(@memo),class:"btn btn-primary mt-4 " %>
<%= link_to '削除する',@memo,method: :delete,data:{confirm:'本当に削除しますか？'},class:"ml-3 btn btn-danger mt-4 " %>
</div>

</article>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>